Feat/add video
CloudCannon/small-business-template-eleventy pull request #11
Opened 2023-09-01 03:38 UTC by James-cloudcannon

# Context

Adds a generic responsive video component that can be used within other components. A user can choose between youtube or vimeo which is set within the `video_source` key. The user can then enter the link into the `video_url` key.

[Link to Notion ticket](https://www.notion.so/cloudcannon/Video-a65cab5c974e4efba24f83851108514a?pvs=4)

# Testing (tester)

The reviewer should check on this branch:

- changing the video source via the `video_source` key
-  adding a link to the `video_url` key.
- The component in Bookshop browser ( generic/video )
- [The site in CloudCannon (link here)](https://app.cloudcannon.com/42158/editor#sites/115950/dashboard/summary)

# Before merge (PR owner)

- Delete the test site in CloudCannon

2023-09-05 23:24 UTC, aleksandrgordeev approved these changes
Works well 👍. The only thing that is missing is the image parameter. I’m not sure if it’s a requirement or not.

Approved considering that either image will be added or ticket description is fixed to remove this parameter.

2023-09-06 11:09 UTC, James-cloudcannon commented
> Works well 👍. The only thing that is missing is the image parameter. I’m not sure if it’s a requirement or not.
> 
> Approved considering that either image will be added or ticket description is fixed to remove this parameter.

Fallback image added. Test by adding an image to to image.src and removing the video_url

2023-09-07 04:17 UTC, aleksandrgordeev commented
Thanks for the changes, @James-cloudcannon. Works well 👍

2023-09-29 03:31 UTC, jtrbuhovic requested changes
Looks great! I made some suggestions to the fallback image input. "src", "alt" etc. probably don't mean much to an editor so I think it's best to be verbose when naming inputs/make them self documenting
<img width="368" alt="Screenshot 2023-09-29 at 4 32 02 PM" src="https://github.com/CloudCannon/small-business-template-eleventy/assets/41709281/137580e9-cef5-46b6-90c0-9a185868c9ad">

2023-09-29 03:31 UTC, jtrbuhovic commented on component-library/components/generic/video/video.bookshop.yml
> +  image:
```suggestion
  fallback_image:
```

2023-09-29 03:31 UTC, jtrbuhovic commented on component-library/components/generic/video/video.bookshop.yml
> +    src:
```suggestion
    image_source: 
```

2023-09-29 03:31 UTC, jtrbuhovic commented on component-library/components/generic/video/video.bookshop.yml
> +    alt:
```suggestion
    alt_description: 
```

2023-09-29 03:31 UTC, jtrbuhovic commented on component-library/components/generic/video/video.bookshop.yml
> +  image:
```suggestion
  fallback_image: 
```

2023-09-29 03:31 UTC, jtrbuhovic commented on component-library/components/generic/video/video.bookshop.yml
> +    src: https://placekitten.com/1000
```suggestion
    image_source: https://placekitten.com/1000
```

2023-09-29 03:31 UTC, jtrbuhovic commented on component-library/components/generic/video/video.bookshop.yml
> +    alt: "A placeholder image"
```suggestion
    alt_description: "A placeholder image"
```

2023-09-29 03:31 UTC, jtrbuhovic commented on component-library/components/generic/video/video.bookshop.yml
> +  src:
```suggestion
  image_source: 
```

2023-09-29 03:31 UTC, jtrbuhovic commented on component-library/components/generic/video/video.eleventy.liquid
> +      <img class="{{ c }}__default-image" src="{{ image.src }}" alt="{{ image.alt }}">
```suggestion
      <img class="{{ c }}__default-image" src="{{ fallback_image.image_source }}" alt="{{ fallback_image.alt_description }}">
```

2023-10-05 07:54 UTC, AlyshaNolan commented
I question the need for this to have a fallback image? The user should never use this component and not provide a video (they should then use the image component). Alternatively, I think that the fallback image should have more meaning and be used while the video is loading or if the link is invalid and fails to load (if that check is possible?)

2023-10-12 22:48 UTC, jtrbuhovic commented
@AlyshaNolan, @James-cloudcannon I've moved the image so it works as a thumbnail/loads before the video

2023-10-13 01:25 UTC, AlyshaNolan approved these changes

2023-10-13 01:26 UTC, merged