Feat/image card
CloudCannon/small-business-template-eleventy pull request #18
Opened 2023-10-13 03:30 UTC by Amber-Song

# Context

Link to [Notion ticket](https://www.notion.so/cloudcannon/Image-Card-d80293c2435749e49c487fc1538bbe63?pvs=4)

# Additional information

Nan

# Testing (tester)

The reviewer should check on this branch:

- The code
- The component in Bookshop browser
- The site in CloudCannon (link here)

# Before merge (PR owner)

- [ ] Delete the test site in CloudCannon
- [ ] For "generic" components **only**: remove `- content_blocks` from `structures` in the YAML file (this was added for testing).

2023-11-01 20:06 UTC, AlyshaNolan commented
From looking at the code I have a couple of thoughts:
    - The gap on the heading component has been changed in the css - this needs to become a dynamic (but probably dev only?) option as the gap is 0.5rem for main components but 0.25rem here.
    - The content p element can use the text-block component (but the frontmatter input will stay the same)
    - I also had some thoughts around the image/icon inputs but I believe Jordan is refactoring that part already

2023-11-14 03:17 UTC, Amber-Song commented
> - The gap on the heading component has been changed in the css - this needs to become a dynamic (but probably dev only?) option as the gap is 0.5rem for main components but 0.25rem here.

Cool.

> The content p element can use the text-block component (but the frontmatter input will stay the same)

Good point! Done!

>  I also had some thoughts around the image/icon inputs but I believe Jordan is refactoring that part already

I saw that changes. I merged in main branch.

2023-11-14 03:30 UTC, Yoda-Soda requested changes

2023-11-14 03:30 UTC, Yoda-Soda commented on component-library/components/simple/image-card/image-card.scss
> +    &--content {
```suggestion
    &__content {
```

2023-11-14 03:30 UTC, Yoda-Soda commented on component-library/components/simple/image-card/image-card.eleventy.liquid
> +    <div class="{{c}}--content">{% bookshop "generic/text-block" bind:content %}</div>
```suggestion
    <div class="{{c}}__content">{% bookshop "generic/text-block" bind:content %}</div>
```

2023-11-14 20:57 UTC, AlyshaNolan commented
I also have a couple more things to request:
- The image component is ready now so the TODO to add it can be replaced
- The button component is ready now so the TODO to replace the link can be completed
- I wonder if it should just be called card? As it works for image and icon
- The change I requested around the heading gap has not changed
- The change around the text block is great but the input should still be a straight input (not using the subcomponent)
- My thoughts around icon/image was turning it into a structure but maybe we revisit this after the other changes I have mentioned

2023-11-14 22:31 UTC, Yoda-Soda approved these changes

2023-11-15 00:05 UTC, Amber-Song commented
> I also have a couple more things to request:
> 
> * The image component is ready now so the TODO to add it can be replaced
> * The button component is ready now so the TODO to replace the link can be completed
> * I wonder if it should just be called card? As it works for image and icon
> * The change I requested around the heading gap has not changed
> * The change around the text block is great but the input should still be a straight input (not using the subcomponent)
> * My thoughts around icon/image was turning it into a structure but maybe we revisit this after the other changes I have mentioned

Done

2023-11-15 03:45 UTC, AlyshaNolan requested changes
- Just realised that it doesn’t really make sense to use the heading subcomponent here as it makes the heading hierarchy incorrect. We either need to change the heading component to let the user pick their hierarchy or just hardcode the heading and eyebrow into the card.
- Needs to be able to change background color
- Image needs to have no padding around it (but icon card needs the padding)
- Allow the user to change the link/button text as well as the url

2023-11-15 03:45 UTC, AlyshaNolan commented on component-library/components/simple/card/card.bookshop.yml
> +  description: Block that contain image and description
```suggestion
  description: Image/icon and a description in a card format
```

2023-11-15 03:45 UTC, AlyshaNolan commented on component-library/components/simple/card/card.scss
> +        font-family: var(--font-family);
```suggestion
```

2023-11-17 01:25 UTC, adon-cloudcannon reviewed
Changes made should be reviewed now... perhaps by @jtrbuhovic with an eye to how it works in the grid?

2023-11-17 01:27 UTC, jtrbuhovic commented
Thanks @adon-cloudcannon! Checking now, I'll make changes in the `feat/add-image-card-grid` branch when fitting these changes in

2023-11-17 01:34 UTC, jtrbuhovic approved these changes
Looks good!

2023-11-17 02:51 UTC, AlyshaNolan approved these changes

2023-11-17 02:54 UTC, merged