Feat/left right blocks
CloudCannon/small-business-template-eleventy pull request #22
Opened 2023-10-31 04:09 UTC by aleksandrgordeev

# Context

Link to [Notion ticket](https://www.notion.so/cloudcannon/Left-Right-Blocks-259af9e8899346f8a5f53cfe006320d4?pvs=4)

# Additional information

Implements Left/Right Blocks. 

# Currently not implemented

A generic button component is still in development so I used a pure HTML button without any styles for now.

# Side changes

1. Set a max-width for stacked labelled icons. This helps to add any amount of icons in a row. Iconst not fitting in one row will be transferred to a second row.
2. Add an uploads folder to build for the user's uploaded assets

# Testing (tester)

The reviewer should check on this branch:

- The code
- The component in Bookshop browser
- The site in CloudCannon (link here)

# Before merge (PR owner)

- [ ] Delete the test site in CloudCannon
- [ ] For "generic" components **only**: remove `- content_blocks` from `structures` in the YAML file (this was added for testing).

2023-11-14 21:18 UTC, AlyshaNolan commented
I started reviewing this and have found a couple things to potentially change:
- Rename key from data -> content (to match other components)
- Description something like -> Content that can be arranged left-right or right-left (rather than mostly repeating the label)
- Make a generic component left right that can take any blocks either side and make specific variants of it (3 different components rather than 1 that handles everything)
- change assign -> assign_local
- Should the content be markdown or just straight text?
- Pass content to text-block (without using text block for the input)

2023-11-14 23:19 UTC, AlyshaNolan requested changes
Please see my comment 😊

2023-11-23 04:46 UTC, AlyshaNolan requested changes
A couple things from me:

- [ ]  I think structures can be used to improve the generic component slightly - I can wheel over to your desk tomorrow to work through this one with you (if you like) as it is a lil complicated
- [ ]  I think the images should be moved from under `style` to under `content`
- [ ] Can `orientation` be made more descriptive to what its for - e.g. `image_alignment` (this is how other components such as hero implement this)
- [ ] Background variants have changed - now `light` -> `primary` and `dark` -> `secondary`
- [ ]  Can we name the blocks left-right-block--{{ component name e.g. testimonial }}

2023-11-23 04:46 UTC, AlyshaNolan commented on component-library/components/sections/testimonial/testimonial.bookshop.yml
> +        - 'Light'
```suggestion
```

2023-11-23 04:46 UTC, AlyshaNolan commented on component-library/components/sections/featured-icons/featured-icons.bookshop.yml
> +        - 'Light'
```suggestion
```

2023-11-23 04:46 UTC, AlyshaNolan commented on component-library/components/sections/featured-icons/featured-icons.bookshop.yml
> +        - 'Light'
This is in the global config

2023-11-23 04:46 UTC, AlyshaNolan commented on component-library/components/sections/featured-icons/featured-icons.eleventy.liquid
> +      TBD after adding custom icons support to labelled-icon
```suggestion
      TODO: after adding custom icons support to labelled-icon
```

2023-11-23 23:21 UTC, AlyshaNolan requested changes
- [x] Can the components use the heading subcomponent - then the capture for the heading could be removed too
- [x] Label should be Left/Right - (name - e.g. Testimonial)
- [ ] Image should be full height

2023-11-23 23:43 UTC, aleksandrgordeev commented on component-library/components/sections/featured-icons/featured-icons.bookshop.yml
> +        - 'Light'
Done

2023-11-23 23:44 UTC, aleksandrgordeev commented on component-library/components/sections/featured-icons/featured-icons.eleventy.liquid
> +      TBD after adding custom icons support to labelled-icon
Thanks for the fix 👍

2023-11-23 23:44 UTC, aleksandrgordeev commented on component-library/components/sections/testimonial/testimonial.bookshop.yml
> +        - 'Light'
Done

2023-11-24 00:03 UTC, AlyshaNolan approved these changes

2023-11-24 00:04 UTC, AlyshaNolan commented
Approved with the assumption components will be removed from the page and uploads will be removed

2023-11-24 00:11 UTC, merged