add footer
CloudCannon/small-business-template-eleventy pull request #29
Opened 2023-11-09 20:55 UTC by Yoda-Soda

# Context

[Link](https://www.notion.so/cloudcannon/Footer-9953e407e1be4827a6d3b7e7d2ba5e1e?pvs=4) to Notion ticket

# Additional information

It's a footer

# Testing (tester)

The reviewer should check on this branch:

- The code
- The site in CloudCannon [(link here)
](https://main-guide.cloudvent.net/)
# Before merge (PR owner)

- [ ] Delete the test site in CloudCannon

2023-11-10 02:35 UTC, aleksandrgordeev requested changes
Footer looks a bit weird on screens smaller than 430 px.

![Screenshot 2023-11-10 at 15 33 43](https://github.com/CloudCannon/small-business-template-eleventy/assets/69171343/c951f663-9285-4a8f-a35a-a7ab1fda2723)

2023-11-10 05:25 UTC, AlyshaNolan commented
Made a couple changes:
- Fix the overflow that @aleksandrgordeev mentioned (not ideal for word logos but better than nothing)
- Switch to using the footer data file rather than the nav data file
- Allow links/bold text/italic text in the copyright section

2023-11-10 05:29 UTC, AlyshaNolan approved these changes

2023-11-14 00:08 UTC, aleksandrgordeev approved these changes
Looks great now 👍

2023-11-14 04:44 UTC, merged