Feat/image + icon card grid
CloudCannon/small-business-template-eleventy pull request #44
Opened 2023-11-23 04:05 UTC by jtrbuhovic

# Context

[Link to Notion ticket](https://www.notion.so/cloudcannon/Icon-Card-Grid-e9c7ab60f3fd4e3ca186c500ad1b073a?pvs=4)
[Link to Notion ticket](https://www.notion.so/cloudcannon/Image-Card-Grid-f5414681fa4542bbbefdc66e3a21f0f9?pvs=4)

# Testing (tester)

The reviewer should check on this branch:

- The code
- The component in Bookshop browser
- The site in CloudCannon ([link here](https://app.cloudcannon.com/42158/editor#sites/118860/dashboard/summary))

# Before merge (PR owner)

- [ ] Delete the test site in CloudCannon
- [ ] For "generic" components **only**: remove `- content_blocks` from `structures` in the YAML file (this was added for testing).

2023-11-23 05:07 UTC, AlyshaNolan requested changes
Couple comments:
icon-card-grid and image-card-grid
- [ ] Need descriptions
- [x] Should be using heading subcomponent
- [x] It seems the styles are doubled up and could be removed from these compoenents (so they both use the styles from card-grid)?

2023-11-23 05:07 UTC, AlyshaNolan commented on component-library/components/generic/button/button.bookshop.yml
> +  id: ""
```suggestion
  onclick: console.log(this)
```

2023-11-23 05:07 UTC, AlyshaNolan commented on component-library/components/generic/button/button.bookshop.yml
> +  id: ""
```suggestion
  onclick: 
```

2023-11-23 05:07 UTC, AlyshaNolan commented on component-library/components/generic/button/button.bookshop.yml
> +  id: ""
Looks like you kept your changes when merging (but main was more updated and should have been kept) - unless you use id but I cant see anywhere that is true

2023-11-23 05:07 UTC, AlyshaNolan commented on component-library/components/generic/button/button.eleventy.liquid
Looks like this branch was kept instead of main - svg_icon should be hero_icon_name

2023-11-23 05:07 UTC, AlyshaNolan commented on component-library/components/generic/card-grid/card-grid.bookshop.yml
Can you please add the relevant fields to the blueprint - otherwise it breaks bookshop browser

2023-11-23 05:07 UTC, AlyshaNolan commented on component-library/components/generic/card-grid/card-grid.eleventy.liquid
> +    </div>
Can this be updated to match the structure other components use - like in centered-large-asset

2023-11-23 05:07 UTC, AlyshaNolan commented on component-library/components/generic/card-grid/card-grid.scss
> +    color: var(--brand-grey-000, #f9f9fb);
```suggestion
```

2023-11-23 05:07 UTC, AlyshaNolan commented on component-library/components/generic/card/card.bookshop.yml
Curious to hear why this card has been kept and the other removed

2023-11-23 05:07 UTC, AlyshaNolan commented on component-library/components/generic/icon/icon.eleventy.liquid
Looks like this branches changes were kept instead of main - svg_icon should be hero_icon_name, icon_style should be icon_type etc

2023-11-23 05:07 UTC, AlyshaNolan commented on component-library/components/sections/featured-map/featured-map.bookshop.yml
I _think_ this component has been completed and merged so this can be removed from this PR

See left-right-block--featured-map on main

2023-11-23 05:07 UTC, AlyshaNolan commented on src/assets/styles/main.scss
Looks like this branch was kept instead of main - should have --full-height option

2023-11-23 21:10 UTC, jtrbuhovic commented on component-library/components/generic/button/button.eleventy.liquid
Fixed with [this commit](https://github.com/CloudCannon/small-business-template-eleventy/pull/44/commits/87f1d2415f9956e9580d653c4699d42e6a92d22c)

2023-11-23 21:13 UTC, jtrbuhovic commented on component-library/components/generic/icon/icon.eleventy.liquid
Fixed with [this commit](https://github.com/CloudCannon/small-business-template-eleventy/pull/44/commits/87f1d2415f9956e9580d653c4699d42e6a92d22c) and [this one](https://github.com/CloudCannon/small-business-template-eleventy/pull/44/commits/e402060731b8c3d0d85aea818520b55c918c05a9)

2023-11-23 23:49 UTC, jtrbuhovic commented on component-library/components/generic/card-grid/card-grid.eleventy.liquid
> +    </div>
Fixed

2023-11-24 00:01 UTC, jtrbuhovic commented on component-library/components/sections/featured-map/featured-map.bookshop.yml
I didn't actually touch this and it's what was merged from merging main into this branch, but I'll delete it anyway in case it's messed anything up

2023-11-24 00:05 UTC, jtrbuhovic commented on src/assets/styles/main.scss
Whoops! fixed

2023-11-24 00:17 UTC, jtrbuhovic commented on component-library/components/generic/card/card.bookshop.yml
The only difference was the use of `imagery` in Adon's `card`, and I felt like it was overkill when you can achieve the same with less code/complexity on this branch. Happy to add it back though if you guys prefer that approach

2023-11-24 04:41 UTC, AlyshaNolan approved these changes

2023-11-24 04:42 UTC, merged