Feat/swap for image component and some touch ups
CloudCannon/small-business-template-eleventy pull request #46
Opened 2023-11-24 00:12 UTC by Yoda-Soda

# Context

[Link](https://www.notion.so/cloudcannon/Add-padding-to-nav-items-23c668d188f242a9b6da7b125c47c7e0?pvs=4) to Notion add padding to nav items
[Link](https://www.notion.so/cloudcannon/Replace-images-161b230a3b29496997df04d432fa7de8?pvs=4) to Notion swap all <img> for image component
[Link](https://www.notion.so/cloudcannon/Nav-animations-22c17fbc3a22478286e632b032fa8b94?pvs=4) to Notion animate mobile nav

# Testing (tester)
 
Make sure to test with and with out image logos for nav and footer. 

The reviewer should check on this branch:

- The code
- The site in CloudCannon ([link](https://app.cloudcannon.com/42158/editor#sites/119070/collections/pages/:/edit?editor=visual&url=%2F&path=%2Fsrc%2Fpages%2Findex.html&collection=pages) here)
- Test site: https://new-flamingo.cloudvent.net/

# Before merge (PR owner)

- [ ] Delete the test site in CloudCannon

2023-11-24 01:18 UTC, AlyshaNolan requested changes
- The text is showing immediately and then the animation is happening on the nav dropdown
- The way the sizes is set needs some work, they don't all have the same sizes so it should be on a per component basis. Thinking we implement it but default to 100vw if the image component isn't passed a sizes param.

2023-11-24 01:49 UTC, AlyshaNolan requested changes
- [ ] The text is showing immediately and then the animation is happening on the nav dropdown
- [ ] Image sizes should be a hidden input

2023-11-24 01:49 UTC, AlyshaNolan commented on component-library/components/generic/image/image.bookshop.yml
> +  image_sizes: 100vh
```suggestion
  image_sizes: 
```

2023-11-24 01:49 UTC, AlyshaNolan commented on component-library/components/generic/image/image.bookshop.yml
> +  image_sizes: 100vh
```suggestion
  image_sizes: 100vw
```

2023-11-24 01:49 UTC, AlyshaNolan commented on component-library/components/generic/image/image.bookshop.yml
> +  image_sizes: 100vh
Otherwise it will always have 100vh

2023-11-24 02:52 UTC, Yoda-Soda commented
I've added a fade in to the text

2023-11-24 03:53 UTC, aleksandrgordeev submitted a review, later dismissed
The bodyscroll lock in mobile view allows to scroll down which makes menu button unavailable. I've attached a video to demonstrate:

https://github.com/CloudCannon/small-business-template-eleventy/assets/69171343/0d9d2f3c-c39d-4176-85c0-2b596439c1e0

2023-11-24 05:58 UTC, Yoda-Soda commented
> The bodyscroll lock in mobile view allows to scroll down which makes menu button unavailable. I've attached a video to demonstrate:
> 
>  Screen.Recording.2023-11-24.at.16.49.38.mov

That's very odd as I can't reproduce this

2023-11-24 18:45 UTC, AlyshaNolan requested changes
- The fade out on the nav items isn't working

I also cannot reproduce the problem that Aleks was having

2023-11-29 00:11 UTC, Yoda-Soda commented
> The fade out on the nav items isn't working
> The fade is also happening on desktop nav
> I also cannot reproduce the problem that Aleks was having

Add the fade for the text. 

Couldn't recreate the fade happening on the desktop. But it's working now so yeah 🥳

2023-11-29 00:30 UTC, AlyshaNolan approved these changes

2023-11-29 00:30 UTC, AlyshaNolan commented
Approved with the condition of blocks being removed from the index page, and the icon put back to original (and the uploaded one being deleted)

2023-11-29 00:35 UTC, merged