Fix/form style
CloudCannon/small-business-template-eleventy pull request #61
Opened 2023-11-30 02:34 UTC by Amber-Song

# Context

Link to [Notion ticket](https://www.notion.so/cloudcannon/Form-fixes-f5653be818dd47859d940f9b1646afdd?pvs=4)

# Additional information

I didn't do the "Comments should be added for form best practices" though.

# Testing (tester)

The reviewer should check on this branch:

- The code
- The component in Bookshop browser
- The site in CloudCannon (link here)

# Before merge (PR owner)

- [ ] Delete the test site in CloudCannon
- [ ] For "generic" components **only**: remove `- content_blocks` from `structures` in the YAML file (this was added for testing).

2023-11-30 02:43 UTC, AlyshaNolan commented
The alignment of the groups was supposed to stay the same - just the comment for the input needed changing

2023-11-30 02:58 UTC, Amber-Song commented
> The alignment of the groups was supposed to stay the same - just the comment for the input needed changing

Ah. Yes. Changed the comment and changed the alignment back.

2023-12-05 19:24 UTC, adon-cloudcannon requested changes
- Checkbox and radio group ‘alignment’ text needs changing - copied from labelled icon and not changed to this context ✅
- If no label is provided for a checkbox/radio group, the little space in the border should be removed (i.e. don’t render an empty element) ✅
- Comments should be added for form best practices - e.g. “You should provide a label for groups” or “You should have at least one radio option checked by default”… something like that? ✅
- Textarea input should have a min-height to stop user from shrinking it too small ✅
- **Bug: radio group - clicking labels doesn’t select the radio input** - this still appears to not work? Just adding a radio button group and adding two buttons, the IDs appear to be the same? Request another look please :)

2023-12-05 21:39 UTC, Amber-Song commented
> * **Bug: radio group - clicking labels doesn’t select the radio input** - this still appears to not work? Just adding a radio button group and adding two buttons, the IDs appear to be the same? Request another look please :)

Good spotting. It is fixed. This is because in ratio button group component radio buttons list, we didn't use bookshop component.

2023-12-05 22:27 UTC, AlyshaNolan commented
It probably shouldn't use the subcomponent but should pass through a UUID for each input

I think the subcomponent shouldn't be used because of the group_name and required inputs

2023-12-07 00:46 UTC, Amber-Song commented
@adon-cloudcannon @AlyshaNolan It works now.

2023-12-07 01:54 UTC, AlyshaNolan commented
There is a typo in the input (ratio_id -> radio_id) and then this looks great other than removing the content blocks from the page 😄

2023-12-07 22:51 UTC, AlyshaNolan approved these changes

2023-12-07 22:51 UTC, AlyshaNolan commented on component-library/components/generic/form/radio-button-group/radio-button-group.bookshop.yml
> +  radio_buttons: [bookshop:generic/form/radio-input]
```suggestion
  radio_buttons:
    - label:
      checked:
      input_id:
```

2023-12-07 22:52 UTC, merged