Chore/components page
CloudCannon/small-business-template-eleventy pull request #97
Opened 2023-12-15 01:34 UTC by adon-cloudcannon

# Context

[Link to Notion ticket](https://www.notion.so/cloudcannon/Component-library-page-broken-5e9bf51ea7934333a42a3ec35401c8ae)

# Additional information

- the components page is back to draft:false
- the components page also gets <meta name=”robots” content=”noindex”> added to the head - I assume this is all that's needed?

# Testing (tester)

The reviewer should check on this branch:

- The code
- The component in Bookshop browser
- The site in CloudCannon [(link here)](https://winged-eraser.cloudvent.net/components/)

# Before merge (PR owner)

- [ ] Delete the test site in CloudCannon
- [ ] For "generic" components **only**: remove `- content_blocks` from `structures` in the YAML file (this was added for testing).

2023-12-20 20:44 UTC, calumocannon requested changes

2023-12-20 20:44 UTC, calumocannon commented on src/_includes/partials/head/meta.html
> +<meta name=”robots” content=”noindex”>
```suggestion
<meta name="robots" content="noindex">
```
I think you have used a slightly different unicode quote or something here ? Shows double in the browser.

![Screenshot 2023-12-21 at 9 42 19 AM](https://github.com/CloudCannon/small-business-template-eleventy/assets/101225153/d0a6e1fd-a927-46dd-be19-3f9964a31314)

2023-12-20 20:49 UTC, calumocannon reviewed
Otherwise it looks good.

2023-12-20 22:09 UTC, adon-cloudcannon commented on src/_includes/partials/head/meta.html
> +<meta name=”robots” content=”noindex”>
And that's why we don't copy and paste from the internet, kids....

2023-12-21 00:26 UTC, calumocannon approved these changes
Nice 👍

2023-12-21 04:15 UTC, merged