Refactor/favicon input
CloudCannon/small-business-template-eleventy pull request #98
Opened 2023-12-18 18:48 UTC by adon-cloudcannon

# Context

[Link to Notion ticket](https://www.notion.so/cloudcannon/Favicon-input-0eab4bae6b704470b2fe15e2509d5683)

# Additional information

- Check input works as image input
- Confirm favicon loads? Image upload works, but favicon not loaded yet - but maybe this takes a little while to come through?

# Testing (tester)

The reviewer should check on this branch:

- The code
- The component in Bookshop browser
- The site in CloudCannon [(link here)](https://app.cloudcannon.com/42158/editor#sites/119944/dashboard/summary:/edit?editor=visual&url=%2F&collection=pages&path=%2Fsrc%2Fpages%2Findex.html)

# Before merge (PR owner)

- [ ] Delete the test site in CloudCannon
- [ ] For "generic" components **only**: remove `- content_blocks` from `structures` in the YAML file (this was added for testing).

2023-12-20 21:21 UTC, calumocannon requested changes
The path for the favicon is pointing at the logo png instead of the favicon svg. I found I was getting a 404 for both the images in the current path so I moved them out of `uploads`

I made a PR in to this one which you can feel free to accept or ignore. It looks scarier than it is due to also merging in main. PR #99

2023-12-20 21:45 UTC, calumocannon commented
Also we should remove the old favicon (Prima Mesa P)

2023-12-20 22:06 UTC, adon-cloudcannon commented
The issue was:

- awhile ago our uploads folder was only src/uploads
- that didn't work for some other scenario, so it was changed to src/assets/uploads
- but the .eleventy.js file was never updated at that same time for the files passthrough
- updated now and the favicon input seems to work 1000000%

2023-12-21 00:22 UTC, calumocannon commented on src/_data/seo.yml
>  title: Primera Mesa
```suggestion
title: Venture
```
Cheeky perhaps but should we update this while we are here ?

2023-12-21 00:23 UTC, calumocannon approved these changes
Very nice 👏 Thanks for the fix.

Approved assuming the testing changes get reverted.

2023-12-21 18:16 UTC, merged